"""empty message

Revision ID: b27241d75edb
Revises: 
Create Date: 2022-08-17 23:18:06.737911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b27241d75edb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name1', sa.String(length=64), nullable=True),
    sa.Column('name2', sa.String(length=64), nullable=True),
    sa.Column('name3', sa.String(length=64), nullable=True),
    sa.Column('name4', sa.String(length=64), nullable=True),
    sa.Column('name5', sa.String(length=64), nullable=True),
    sa.Column('name6', sa.String(length=64), nullable=True),
    sa.Column('school1', sa.String(length=64), nullable=True),
    sa.Column('school2', sa.String(length=64), nullable=True),
    sa.Column('school3', sa.String(length=64), nullable=True),
    sa.Column('school4', sa.String(length=64), nullable=True),
    sa.Column('school5', sa.String(length=64), nullable=True),
    sa.Column('school6', sa.String(length=64), nullable=True),
    sa.Column('email1', sa.String(length=64), nullable=True),
    sa.Column('emailb', sa.String(length=64), nullable=True),
    sa.Column('phone1', sa.Integer(), nullable=True),
    sa.Column('phoneb', sa.Integer(), nullable=True),
    sa.Column('interest', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
